#### #----#                    Docstring                    #----# ####
#' Title:  COVID_VACCINE_FLOW_IDS
#' Project:  FGH COVID Vaccine DAH Project 2021- Finalize data compile
#' Purpose : Names for the entity ids for the Covid Vaccine Project
#---------------------------------------------------------------------#

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#' Note: 
#'      If need be to update the entity ids and names list or add more
#'      make sure to maintain the structure and that the code changes
#'      appropiately to represent the update to the IDs
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

################### #----# ENVIRONMENT SETUP #----# ###################

#----# Set up directory roots #----#
#----# List Definition #----#

COVID_VACCINE_FLOW_IDS <- list(
  1 = 'African Development Bank' , 
  2 = 'Asian Development Bank' , 
  3 = 'Australia' , 
  4 = 'Austria' , 
  5 = 'Belgium' , 
  6 = 'BMGF' , 
  7 = 'Canada' , 
  8 = 'Newborn and child health' , 
  9 = 'Newborn and child health nutrition' , 
  10 = 'Newborn and child health other system support' , 
  11 = 'Corporate donations' , 
  12 = 'Debt repayments' , 
  13 = 'Denmark' , 
  14 = 'Development banks' , 
  15 = 'Southeast Asia, East Asia, and Oceania' , 
  16 = 'Central Europe, Eastern Europe, and Central Asia' , 
  17 = 'European Commission' , 
  18 = 'Family planning' , 
  19 = 'Finland' , 
  20 = 'France' , 
  21 = 'Gavi' , 
  22 = 'Germany' , 
  23 = 'Global Fund' , 
  24 = 'Global' , 
  25 = 'Greece' , 
  26 = 'HIV/AIDS' , 
  27 = 'HIV/AIDS care and support' , 
  28 = 'HIV/AIDS counseling/testing' , 
  29 = 'HIV/AIDS prevention' , 
  30 = 'HIV/AIDS other system support' , 
  31 = 'HIV/AIDS TB coinfection' , 
  32 = 'HIV/AIDS treatment' , 
  33 = 'Inter-American Development Bank' , 
  34 = 'Ireland' , 
  35 = 'Italy' , 
  36 = 'Japan' , 
  37 = 'South Korea' , 
  38 = 'Latin America and Caribbean' , 
  39 = 'Luxembourg' , 
  40 = 'Malaria' , 
  41 = 'Malaria - Community outreach' , 
  42 = 'Malaria - Diagnosis' , 
  43 = 'Malaria - Other health system support' , 
  44 = 'Malaria - Indoor residual spraying' , 
  45 = 'Malaria - nets' , 
  46 = 'Malaria - Other control' , 
  47 = 'Malaria - Treatment' , 
  48 = 'Malaria - Other' , 
  49 = 'Reproductive and maternal health' , 
  50 = 'Reproductive and maternal other systems support' , 
  51 = 'Mental health' , 
  52 = 'North Africa and Middle East' , 
  53 = 'Noncommunicable diseases other health systems support' , 
  54 = 'Netherlands' , 
  55 = 'New Zealand' , 
  56 = 'NGOs & foundations' , 
  57 = 'Non-OECD DAC countries' , 
  58 = 'Noncommunicable diseases' , 
  59 = 'Norway' , 
  60 = 'Orphans/vulnerable children' , 
  61 = 'Other bilateral aid agencies' , 
  62 = 'Other governments' , 
  63 = 'Other health focus areas' , 
  64 = 'Other infectious diseases' , 
  65 = 'Maternal health' , 
  66 = 'Other private' , 
  67 = 'Other sources' , 
  68 = 'PAHO' , 
  69 = 'PMTCT' , 
  70 = 'Portugal' , 
  71 = 'Private philanthropy' , 
  72 = 'South Asia' , 
  73 = 'Spain' , 
  74 = 'Sub-Saharan Africa' , 
  75 = 'SWAps & HSS' , 
  76 = 'Sweden' , 
  77 = 'Switzerland' , 
  78 = 'Tobacco' , 
  79 = 'Tuberculosis' , 
  80 = 'UN agencies' , 
  81 = 'UNAIDS' , 
  82 = 'Unallocable' , 
  83 = 'UNFPA' , 
  84 = 'UNICEF' , 
  85 = 'Other Noncommunicable diseases ' , 
  86 = 'Other newborn and child health' , 
  87 = 'Other HIV/AIDS' , 
  88 = 'Other maternal and reproductive health' , 
  89 = 'United Kingdom' , 
  90 = 'United States' , 
  91 = 'Vaccines' , 
  92 = 'WHO' , 
  93 = 'World Bank - IBRD' , 
  94 = 'World Bank - IDA' , 
  95 = 'All sources' , 
  96 = 'All channels' , 
  97 = 'All HFAs' , 
  98 = 'All region' , 
  99 = 'Other sources' , 
  100 = 'Other infectious diseases other health systems support' , 
  101 = 'Other infectious diseases - other' , 
  102 = 'Tuberculosis other health systems support' , 
  103 = 'Tuberculosis - Other' , 
  104 = 'Other child health' , 
  105 = 'Tuberculosis - Treatment' , 
  106 = 'Tuberculosis - Diagnosis' , 
  107 = 'Tuberculosis - Antimicrobial resistance' , 
  108 = 'Malaria - Antimicrobial resistance' , 
  109 = 'HIV/AIDS antimicrobial resistance' , 
  110 = 'Other infectious diseases - Antimicrobial resistance' , 
  111 = 'Other infectious diseases - Ebola' , 
  112 = 'Other infectious diseases - Zika' , 
  113 = 'UNITAID' , 
  114 = 'United Arab Emirates' , 
  115 = 'HSS - Pandemic Preparedness' , 
  116 = 'SWAps & HSS - other' , 
  117 = 'China' , 
  118 = 'Other OECD DAC countries' , 
  119 = 'CEPI' , 
  120 = 'European Economic Area' , 
  121 = 'Wellcome Trust' , 
  122 = 'HIV/AIDS human resources' , 
  123 = 'Malaria human resources' , 
  124 = 'Noncommunicable diseases human resources' , 
  125 = 'Newborn and child health system support' , 
  126 = 'Other infectious diseases human resources' , 
  127 = 'Reproductive and maternal health human resources' , 
  128 = 'SWAps & HSS - human resources' , 
  129 = 'Tuberculosis human resources' , 
  130 = 'COVID-19 Vaccine - Demand creation and social mobilization' , 
  131 = 'COVID-19 Vaccine - Supply chain' , 
  132 = 'COVID-19 Vaccine - Monitoring' , 
  133 = 'COVID-19 Vaccine - Waste management' , 
  134 = 'COVID-19 Vaccine - Human resources' , 
  135 = 'COVID-19 Vaccine - Technical assistance' , 
  136 = 'COVID-19 Vaccine - Planning and coordination' , 
  137 = 'COVID-19 Vaccine - Distribution and outreach' , 
  138 = 'COVID-19 Vaccine - Safety' , 
  139 = 'COVID-19 Vaccine - Vaccine delivery'
)

